from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

import app.workflow as workflow_module
from app.providers import MockAvatarVideoProvider
from app.storage import Repository
from app.text_extraction import TextExtractionRouter
from app.workflow import WorkflowService


class WorkflowServiceTest(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name)
        self.repository = Repository(self.root / "app.db")
        self.repository.init_schema()
        self.workflow = WorkflowService(self.repository)

    def test_project_processing_creates_review_ready_artifacts(self) -> None:
        # Test objective:
        # Verify that one link-based project can move through the MVP ingestion workflow
        # and reach the human review state with all required review artifacts present.
        #
        # Construction method:
        # 1. Build a temporary SQLite repository so the test has isolated state.
        # 2. Create a link project using the same source fields accepted by the API.
        # 3. Run the workflow synchronously to avoid timing assumptions from background threads.
        #
        # Input data:
        # The source is a Douyin-style link record with a reference title, a separate
        # target topic for the new script, platform, URL, and user notes.
        #
        # Expected behavior:
        # The project status becomes ready_for_review, one editable transcript is stored,
        # one structured analysis is stored, and exactly three draft script versions are stored.
        # Structure analysis remains about the reference video title, while generated
        # scripts use the selected target topic as the new content theme.
        project = self.repository.create_project(
            {
                "source_type": "link",
                "source_url": "https://example.test/video/123",
                "platform": "douyin",
                "title": "职场沟通的三个误区",
                "target_topic": "AI 编程工具怎么影响普通开发者",
                "notes": "目标观众是刚入职新人",
            }
        )

        self.workflow.process_project(project["id"])

        detail = self.repository.get_project_detail(project["id"])
        self.assertIsNotNone(detail)
        assert detail is not None
        self.assertEqual(detail["status"], "ready_for_review")
        self.assertEqual(detail["transcript"]["extraction_method"], "speech")
        self.assertTrue(detail["transcript"]["warnings"])
        self.assertEqual(detail["analysis"]["topic"], "职场沟通的三个误区")
        self.assertEqual(len(detail["scripts"]), 3)
        self.assertTrue(all(script["status"] == "draft" for script in detail["scripts"]))
        self.assertIn("AI 编程工具怎么影响普通开发者", detail["scripts"][0]["script_text"])
        self.assertNotIn("很多人做职场沟通的三个误区", detail["scripts"][0]["script_text"])
        self.assertNotIn("写作模式", detail["scripts"][0]["script_text"])
        self.assertNotIn("目标主题素材", detail["scripts"][0]["script_text"])
        self.assertNotIn("这版适合", detail["scripts"][0]["script_text"])

    def test_render_requires_approved_script(self) -> None:
        # Test objective:
        # Verify that the digital-human render workflow enforces the required human
        # approval gate before a draft artifact can be generated.
        #
        # Construction method:
        # 1. Process a project to generate draft scripts.
        # 2. Create a render job directly for the first draft script and run rendering.
        # 3. Approve the same script, create a second render job, and run rendering again.
        #
        # Input data:
        # The script is generated by the mock LLM provider from a link project.
        #
        # Expected behavior:
        # The unapproved script render fails with a clear state-transition error.
        # After approval, rendering succeeds and produces a downloadable local artifact path.
        project = self.repository.create_project(
            {
                "source_type": "link",
                "source_url": "https://example.test/video/456",
                "platform": "douyin",
                "title": "内容改写流程",
                "notes": "",
            }
        )
        self.workflow.process_project(project["id"])
        script = self.repository.list_scripts(project["id"])[0]

        failed_job = self.repository.create_render_job(script, MockAvatarVideoProvider.name)
        self.workflow.render_script(script["id"], failed_job["id"])
        failed_job = self.repository.get_render_job(failed_job["id"])
        self.assertIsNotNone(failed_job)
        assert failed_job is not None
        self.assertEqual(failed_job["status"], "failed")
        self.assertIn("approved", failed_job["error_message"])

        approved_script = self.repository.approve_script(script["id"])
        self.assertIsNotNone(approved_script)
        assert approved_script is not None
        succeeded_job = self.repository.create_render_job(approved_script, MockAvatarVideoProvider.name)

        old_output_dir = workflow_module.OUTPUT_DIR
        workflow_module.OUTPUT_DIR = self.root / "outputs"
        try:
            self.workflow.render_script(approved_script["id"], succeeded_job["id"])
        finally:
            workflow_module.OUTPUT_DIR = old_output_dir

        succeeded_job = self.repository.get_render_job(succeeded_job["id"])
        self.assertIsNotNone(succeeded_job)
        assert succeeded_job is not None
        self.assertEqual(succeeded_job["status"], "succeeded")
        self.assertTrue(succeeded_job["output_video_url"].startswith("/outputs/render-"))

    def test_text_extraction_router_selects_requested_strategies(self) -> None:
        # Test objective:
        # Verify that the text extraction router honors the user's selected extraction
        # condition and exposes enough metadata for the UI to explain the route used.
        #
        # Construction method:
        # 1. Create a temporary subtitle file that represents an uploaded local source.
        # 2. Call the router once with the explicit subtitle-track preference.
        # 3. Call the router once with a link source in auto mode.
        #
        # Input data:
        # The local source is an SRT-style text file; the network source is an example URL.
        #
        # Expected behavior:
        # The subtitle preference returns cleaned subtitle text without needing FFmpeg.
        # The link auto mode plans through network captions and falls back with warnings
        # when network fetching is not explicitly enabled.
        subtitle_path = self.root / "sample.srt"
        subtitle_path.write_text(
            "1\n00:00:00,000 --> 00:00:02,000\n第一句字幕\n\n2\n00:00:02,000 --> 00:00:04,000\n第二句字幕\n",
            encoding="utf-8",
        )
        router = TextExtractionRouter()

        subtitle_result = router.extract(
            source=workflow_module.SourceInput(
                source_type="upload",
                title="字幕测试",
                platform="local",
                source_url=None,
                source_file_path=str(subtitle_path),
                notes="",
            ),
            preference="subtitle_track",
        )

        self.assertEqual(subtitle_result["extraction_method"], "subtitle_track")
        self.assertEqual(subtitle_result["provider"], "sidecar-subtitle")
        self.assertIn("第一句字幕", subtitle_result["raw_text"])

        network_result = router.extract(
            source=workflow_module.SourceInput(
                source_type="link",
                title="网络字幕测试",
                platform="web",
                source_url="https://example.test/video",
                source_file_path=None,
                notes="",
            ),
            preference="auto",
        )

        self.assertEqual(network_result["extraction_method"], "speech")
        self.assertTrue(any("网络字幕抓取默认关闭" in item for item in network_result["warnings"]))
        self.assertEqual(
            router.plan(
                workflow_module.SourceInput(
                    source_type="upload",
                    title="本地视频",
                    platform="local",
                    source_url=None,
                    source_file_path="local.mp4",
                    notes="",
                ),
                "auto",
            ),
            ["subtitle_track", "speech", "screen_text"],
        )

    def test_auto_extraction_prefers_local_media_for_link_projects(self) -> None:
        # Test objective:
        # Verify that a link project with an attached local media/subtitle file is
        # processed on the server from that file instead of being blocked by network
        # caption compliance limits.
        #
        # Construction method:
        # 1. Create a temporary sidecar subtitle file representing user-provided media text.
        # 2. Create a link-style SourceInput that includes both source_url and source_file_path.
        # 3. Run auto extraction through the router.
        #
        # Input data:
        # A Douyin-like link with a local SRT file attached to the project.
        #
        # Expected behavior:
        # Auto mode uses the local subtitle-track route and returns real sidecar text,
        # not the network-captions fallback warning for Douyin URLs.
        subtitle_path = self.root / "douyin-export.srt"
        subtitle_path.write_text(
            "1\n00:00:00,000 --> 00:00:02,000\n本地文件字幕内容\n",
            encoding="utf-8",
        )
        router = TextExtractionRouter()

        result = router.extract(
            source=workflow_module.SourceInput(
                source_type="link",
                title="链接加本地文件",
                platform="douyin",
                source_url="https://www.douyin.com/video/123",
                source_file_path=str(subtitle_path),
                notes="",
            ),
            preference="auto",
        )

        self.assertEqual(result["extraction_method"], "subtitle_track")
        self.assertEqual(result["provider"], "sidecar-subtitle")
        self.assertIn("本地文件字幕内容", result["raw_text"])
        self.assertFalse(any("不抓取抖音链接字幕" in item for item in result["warnings"]))


if __name__ == "__main__":
    unittest.main()
